import Link from 'next/link';
import { ArrowRight, Check, ShieldCheck, FileCheck2, MessagesSquare } from 'lucide-react';
const services = [{slug:'tourist', title:'Tourist visa assistance', text:'Prepare a clear application for holidays, visits and short stays.'},{slug:'business', title:'Business visa assistance', text:'Organise documentation for meetings, conferences and commercial travel.'},{slug:'student', title:'Student visa assistance', text:'Get practical guidance for study applications and supporting evidence.'},{slug:'family', title:'Family visa assistance', text:'Navigate family visits and reunification documentation with confidence.'},{slug:'work', title:'Work visa assistance', text:'Understand employer, role and documentation requirements before applying.'},{slug:'transit', title:'Transit visa assistance', text:'Check transit rules and plan your route without avoidable surprises.'}];
export default function HomePage() { return <>
<section className="bg-gradient-to-br from-blue-950 via-blue-900 to-indigo-900 px-4 py-24 text-white"><div className="mx-auto max-w-6xl"><p className="mb-4 font-bold uppercase tracking-[.2em] text-amber-300">M TRAVEL'S</p><h1 className="max-w-4xl text-4xl font-black leading-tight sm:text-6xl">Visa assistance made simple, clear and personal.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-blue-100">We help you understand every stage of your visa journey, organise your documents and prepare with confidence. No confusing promises—just practical guidance.</p><div className="mt-9 flex flex-wrap gap-4"><Link className="rounded-xl bg-amber-400 px-6 py-3 font-bold text-slate-950" href="/contact">Speak to a visa expert <ArrowRight className="ml-2 inline" size={18}/></Link><Link className="rounded-xl border border-white/40 px-6 py-3 font-bold" href="/visa-check">Start your visa check</Link></div></div></section>
<section className="mx-auto max-w-6xl px-4 py-16"><div className="grid gap-6 md:grid-cols-3"><div className="rounded-2xl bg-blue-50 p-6"><ShieldCheck className="text-blue-800"/><h2 className="mt-4 text-xl font-bold">Clear guidance</h2><p className="mt-2 text-slate-600">Understand the rules and next steps for your destination.</p></div><div className="rounded-2xl bg-amber-50 p-6"><FileCheck2 className="text-amber-700"/><h2 className="mt-4 text-xl font-bold">Document support</h2><p className="mt-2 text-slate-600">Know what evidence is needed and how to prepare it properly.</p></div><div className="rounded-2xl bg-emerald-50 p-6"><MessagesSquare className="text-emerald-700"/><h2 className="mt-4 text-xl font-bold">Human support</h2><p className="mt-2 text-slate-600">Ask questions and get help throughout the process.</p></div></div></section>
<section className="bg-slate-50 px-4 py-16"><div className="mx-auto max-w-6xl"><h2 className="text-3xl font-black">Visa services</h2><p className="mt-3 max-w-2xl text-slate-600">Choose the journey that matches your plans. Requirements vary by destination and nationality, so contact us for personalised guidance.</p><div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{services.map(s=><Link key={s.slug} href={`/services/${s.slug}`} className="rounded-2xl border bg-white p-6 transition hover:-translate-y-1 hover:shadow-lg"><h3 className="text-xl font-bold">{s.title}</h3><p className="mt-3 text-slate-600">{s.text}</p><span className="mt-5 inline-block font-bold text-blue-800">Learn about the process →</span></Link>)}</div></div></section>
<section className="mx-auto max-w-6xl px-4 py-16"><h2 className="text-3xl font-black">Our step-by-step approach</h2><div className="mt-8 grid gap-4 md:grid-cols-5">{['Eligibility check','Document review','Application preparation','Submission support','Follow-up guidance'].map((x,i)=><div className="rounded-xl border p-5" key={x}><div className="text-2xl font-black text-amber-600">0{i+1}</div><h3 className="mt-3 font-bold">{x}</h3><p className="mt-2 text-sm text-slate-600">We help you move forward with fewer avoidable errors.</p></div>)}</div></section>
<section className="bg-amber-400 px-4 py-14 text-center"><h2 className="text-3xl font-black text-slate-950">Ready to discuss your visa journey?</h2><p className="mx-auto mt-3 max-w-xl text-slate-800">Every case is different. Contact M TRAVEL'S and let our team explain how we can help.</p><Link href="/contact" className="mt-6 inline-block rounded-xl bg-blue-950 px-6 py-3 font-bold text-white">Contact us for assistance</Link></section>
</>; }
