export const APP_CONFIG = {
  name: 'M Travels - Visa Services',
  description: 'Expert visa services and guidance for international travel',
  url: process.env.NEXT_PUBLIC_APP_URL || 'https://m-travels.com',
  apiUrl: process.env.NEXT_PUBLIC_API_URL || 'https://api.m-travels.com',
  socialLinks: {
    facebook: 'https://facebook.com/mtravelsvisa',
    twitter: 'https://twitter.com/mtravelsvisa',
    instagram: 'https://instagram.com/mtravelsvisa',
    linkedin: 'https://linkedin.com/company/mtravelsvisa',
  },
  contact: {
    email: 'support@m-travels.com',
    phone: '+1-800-VISA-HELP',
    address: '123 Travel Street, City, Country',
  },
};

export const VISA_COUNTRIES = [
  { code: 'US', name: 'United States', flag: '🇺🇸' },
  { code: 'UK', name: 'United Kingdom', flag: '🇬🇧' },
  { code: 'CA', name: 'Canada', flag: '🇨🇦' },
  { code: 'AU', name: 'Australia', flag: '🇦🇺' },
  { code: 'DE', name: 'Germany', flag: '🇩🇪' },
  { code: 'FR', name: 'France', flag: '🇫🇷' },
  { code: 'JP', name: 'Japan', flag: '🇯🇵' },
  { code: 'SG', name: 'Singapore', flag: '🇸🇬' },
  { code: 'AE', name: 'United Arab Emirates', flag: '🇦🇪' },
  { code: 'NZ', name: 'New Zealand', flag: '🇳🇿' },
  { code: 'IE', name: 'Ireland', flag: '🇮🇪' },
  { code: 'CH', name: 'Switzerland', flag: '🇨🇭' },
  { code: 'SG', name: 'Singapore', flag: '🇸🇬' },
  { code: 'MY', name: 'Malaysia', flag: '🇲🇾' },
  { code: 'TH', name: 'Thailand', flag: '🇹🇭' },
];

export const VISA_TYPES = [
  { id: 'tourist', name: 'Tourist Visa', icon: '🏖️' },
  { id: 'business', name: 'Business Visa', icon: '💼' },
  { id: 'work', name: 'Work Visa', icon: '👔' },
  { id: 'student', name: 'Student Visa', icon: '🎓' },
  { id: 'family', name: 'Family Visa', icon: '👨‍👩‍👧‍👦' },
  { id: 'transit', name: 'Transit Visa', icon: '✈️' },
];

export const DOCUMENT_CATEGORIES = [
  'Personal Documents',
  'Financial Documents',
  'Employment Documents',
  'Educational Documents',
  'Travel Documents',
  'Medical Documents',
  'Accommodation Documents',
];

export const PROCESSING_TIMES = [
  { value: '1-5', label: '1-5 days' },
  { value: '6-10', label: '6-10 days' },
  { value: '11-20', label: '11-20 days' },
  { value: '21-30', label: '21-30 days' },
  { value: '30+', label: '30+ days' },
];

export const NATIONALITIES = [
  'Afghan',
  'Albanian',
  'Algerian',
  'American',
  'Andorran',
  'Angolan',
  'Argentine',
  'Armenian',
  'Australian',
  'Austrian',
  'Azerbaijani',
  'Bahamian',
  'Bahraini',
  'Bangladeshi',
  'Barbadian',
  'Belarusian',
  'Belgian',
  'Belizean',
  'Beninese',
  'Bhutanese',
  'Bolivian',
  'Bosnian',
  'Botswanan',
  'Brazilian',
  'British',
  'Bruneian',
  'Bulgarian',
  'Burkinabe',
  'Burundian',
  'Cambodian',
  'Cameroonian',
  'Canadian',
  'Cape Verdean',
  'Central African',
  'Chadian',
  'Chilean',
  'Chinese',
  'Colombian',
  'Comorian',
  'Congolese',
  'Costa Rican',
  'Croatian',
  'Cuban',
  'Cypriot',
  'Czech',
  'Danish',
  'Djiboutian',
  'Dominican',
  'Dutch',
  'East Timorese',
  'Ecuadorian',
  'Egyptian',
  'Emirati',
  'Equatorial Guinean',
  'Eritrean',
  'Estonian',
  'Ethiopian',
  'Fijian',
  'Filipino',
  'Finnish',
  'French',
  'Gabonese',
  'Gambian',
  'Georgian',
  'German',
  'Ghanaian',
  'Greek',
  'Grenadian',
  'Guatemalan',
  'Guinean',
  'Guinea-Bissauan',
  'Guyanese',
  'Haitian',
  'Herzegovinian',
  'Honduran',
  'Hungarian',
  'Icelandic',
  'Indian',
  'Indonesian',
  'Iranian',
  'Iraqi',
  'Irish',
  'Israeli',
  'Italian',
  'Ivorian',
  'Jamaican',
  'Japanese',
  'Jordanian',
  'Kazakhstani',
  'Kenyan',
  'Kittitian',
  'Kuwaiti',
  'Kyrgyzstani',
  'Laotian',
  'Latvian',
  'Lebanese',
  'Lesothoan',
  'Liberian',
  'Libyan',
  'Liechtenstein',
  'Lithuanian',
  'Luxembourgish',
  'Macedonian',
  'Malagasy',
  'Malawian',
  'Malaysian',
  'Maldivian',
  'Malian',
  'Maltese',
  'Marshallese',
  'Martiniquais',
  'Mauritanian',
  'Mauritian',
  'Mexican',
  'Micronesian',
  'Moldovan',
  'Monacan',
  'Mongolian',
  'Montenegrin',
  'Moroccan',
  'Mozambican',
  'Myanmar',
  'Namibian',
  'Nauruan',
  'Nepalese',
  'New Zealander',
  'Nicaraguan',
  'Nigerian',
  'North Korean',
  'Northern Irish',
  'Norwegian',
  'Omani',
  'Pakistani',
  'Palauan',
  'Palestinian',
  'Panamanian',
  'Papua New Guinean',
  'Paraguayan',
  'Peruvian',
  'Polish',
  'Portuguese',
  'Qatari',
  'Romanian',
  'Russian',
  'Rwandan',
  'Saint Helenian',
  'Saint Kittsian',
  'Saint Lucian',
  'Saint Vincentian',
  'Samoan',
  'Sammarinese',
  'Sao Tomean',
  'Saudi',
  'Scottish',
  'Senegalese',
  'Serbian',
  'Seychellois',
  'Sierra Leonean',
  'Singaporean',
  'Slovak',
  'Slovenian',
  'Solomon Islander',
  'Somali',
  'South African',
  'South Korean',
  'South Sudanese',
  'Spanish',
  'Sri Lankan',
  'Sudanese',
  'Surinamese',
  'Swazi',
  'Swedish',
  'Swiss',
  'Syrian',
  'Taiwanese',
  'Tajikistani',
  'Tanzanian',
  'Thai',
  'Togolese',
  'Tongan',
  'Trinidadian',
  'Tunisian',
  'Turkish',
  'Turkmenistani',
  'Tuvaluan',
  'Ugandan',
  'Ukrainian',
  'Uruguayan',
  'Uzbekistani',
  'Vanuatuan',
  'Venezuelan',
  'Vietnamese',
  'Virgin Islander',
  'Welsh',
  'Yemeni',
  'Zambian',
  'Zimbabwean',
];

export const TRAVEL_PURPOSES = [
  { value: 'tourism', label: 'Tourism & Leisure' },
  { value: 'business', label: 'Business Meeting' },
  { value: 'conference', label: 'Conference' },
  { value: 'education', label: 'Education' },
  { value: 'work', label: 'Work/Employment' },
  { value: 'family', label: 'Family Visit' },
  { value: 'medical', label: 'Medical Treatment' },
  { value: 'transit', label: 'Transit' },
  { value: 'other', label: 'Other' },
];

export const ERROR_MESSAGES = {
  INVALID_EMAIL: 'Please enter a valid email address',
  INVALID_PASSWORD: 'Password must be at least 8 characters',
  PASSWORDS_MISMATCH: 'Passwords do not match',
  USER_ALREADY_EXISTS: 'This email is already registered',
  INVALID_CREDENTIALS: 'Invalid email or password',
  SESSION_EXPIRED: 'Your session has expired. Please login again',
  UNAUTHORIZED: 'You do not have permission to perform this action',
  SERVER_ERROR: 'An error occurred. Please try again later',
  FILE_TOO_LARGE: 'File size exceeds maximum limit (10MB)',
  INVALID_FILE_TYPE: 'Invalid file type. Please upload a valid document',
};

export const SUCCESS_MESSAGES = {
  ACCOUNT_CREATED: 'Account created successfully',
  LOGIN_SUCCESS: 'Logged in successfully',
  LOGOUT_SUCCESS: 'Logged out successfully',
  PROFILE_UPDATED: 'Profile updated successfully',
  APPLICATION_SUBMITTED: 'Application submitted successfully',
  DOCUMENT_UPLOADED: 'Document uploaded successfully',
  PASSWORD_RESET: 'Password reset email sent',
};
